---
dev_addr: "127.0.0.1:8001"
edit_uri: "edit/develop/docs"
site_dir: "nautobot_device_onboarding/static/nautobot_device_onboarding/docs"
site_name: "Device Onboarding Documentation"
site_url: "https://docs.nautobot.com/projects/device-onboarding/en/latest/"
repo_url: "https://github.com/nautobot/nautobot-plugin-device-onboarding"
copyright: "Copyright &copy; The Authors"
theme:
  name: "material"
  navigation_depth: 4
  custom_dir: "docs/assets/overrides"
  hljs_languages:
    - "django"
    - "yaml"
  features:
    - "navigation.tracking"
    - "navigation.tabs"
    - "navigation.tabs.sticky"
    - "search.suggest"
    - "search.highlight"
    - "search.share"
    - "navigation.indexes"
  favicon: "assets/favicon.ico"
  logo: "assets/nautobot_logo.svg"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: "default"
      primary: "black"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to dark mode"

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: "slate"
      primary: "black"
      toggle:
        icon: "material/weather-night"
        name: "Switch to light mode"
extra_css:
  - "assets/extra.css"

# needed for RTD version flyout menu
# jquery is not (yet) injected by RTD automatically and it might be dropped
# as a dependency in the future
extra_javascript:
  - "https://code.jquery.com/jquery-3.6.0.min.js"

extra:
  generator: false
  ntc_sponsor: true
  social:
    - icon: "fontawesome/solid/rss"
      link: "https://blog.networktocode.com/blog/tags/nautobot"
      name: "Network to Code Blog"
    - icon: "fontawesome/brands/youtube"
      link: "https://www.youtube.com/playlist?list=PLjA0bhxgryJ2Ts4GJMDA-tPzVWEncv4pb"
      name: "Nautobot Videos"
    - icon: "fontawesome/brands/slack"
      link: "https://www.networktocode.com/community/"
      name: "Network to Code Community"
    - icon: "fontawesome/brands/github"
      link: "https://github.com/nautobot/nautobot"
      name: "GitHub Repo"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/networktocode"
      name: "Network to Code Twitter"
markdown_extensions:
  - "admonition"
  - "toc":
      permalink: true
  - "attr_list"
  - "md_in_html"
  - "pymdownx.highlight":
      anchor_linenums: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences"
  - "footnotes"
plugins:
  - "search"
  - "mkdocs-version-annotations"
  - "mkdocstrings":
      default_handler: "python"
      handlers:
        python:
          paths: ["."]
          options:
            show_root_heading: true
watch:
  - "README.md"

nav:
  - Overview: "index.md"
  - User Guide:
      - App Overview: "user/app_overview.md"
      - Getting Started: "user/app_getting_started.md"
      - Using the App: "user/app_use_cases.md"
      - Frequently Asked Questions: "user/faq.md"
      - External Interactions: "user/external_interactions.md"
  - Administrator Guide:
      - Install and Configure: "admin/install.md"
      - Upgrade: "admin/upgrade.md"
      - Uninstall: "admin/uninstall.md"
      - Compatibility Matrix: "admin/compatibility_matrix.md"
      - Release Notes:
          - "admin/release_notes/index.md"
          - v2.0: "admin/release_notes/version_2.0.md"
          - v1.2: "admin/release_notes/version_1.2.md"
          - v1.1: "admin/release_notes/version_1.1.md"
          - v1.0: "admin/release_notes/version_1.0.md"
  - Developer Guide:
      - Extending the App: "dev/extending.md"
      - Onboarding Extensions: "dev/onboarding_extensions.md"
      - Contributing to the App: "dev/contributing.md"
      - Development Environment: "dev/dev_environment.md"
      - Code Reference:
          - "dev/code_reference/index.md"
          - Models: "dev/code_reference/models.md"
          - API: "dev/code_reference/api.md"
  - Nautobot Docs Home ↗︎: "https://docs.nautobot.com"
