# Generated by Django 3.1.3 on 2021-02-22 03:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dcim", "0004_initial_part_4"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("ip_address", models.CharField(max_length=255, null=True)),
                ("device_type", models.CharField(max_length=255, null=True)),
                ("status", models.CharField(max_length=255)),
                ("failed_reason", models.CharField(max_length=255, null=True)),
                ("message", models.CharField(blank=True, max_length=511)),
                ("port", models.PositiveSmallIntegerField(default=22)),
                ("timeout", models.PositiveSmallIntegerField(default=30)),
                (
                    "created_device",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="dcim.device"
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="dcim.platform"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="dcim.devicerole"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="dcim.site"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OnboardingDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("device", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="dcim.device")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
