# Generated by Django 4.2.21 on 2025-05-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ("nautobot_device_onboarding", "0001_squash__0001_0004_0005_0006"),
        ("nautobot_device_onboarding", "0002_create_onboardingdevice"),
        ("nautobot_device_onboarding", "0003_onboardingtask_label"),
        ("nautobot_device_onboarding", "0007_alter_onboardingtask_ip_address"),
        ("nautobot_device_onboarding", "0008_alter_onboardingtask_options"),
        ("nautobot_device_onboarding", "0009_remove_models"),
    ]

    initial = True
