# Generated by Django 3.2.21 on 2023-11-17 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_device_onboarding", "0008_alter_onboardingtask_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="onboardingtask",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="onboardingtask",
            name="created_device",
        ),
        migrations.RemoveField(
            model_name="onboardingtask",
            name="location",
        ),
        migrations.RemoveField(
            model_name="onboardingtask",
            name="platform",
        ),
        migrations.RemoveField(
            model_name="onboardingtask",
            name="role",
        ),
        migrations.DeleteModel(
            name="OnboardingDevice",
        ),
        migrations.DeleteModel(
            name="OnboardingTask",
        ),
    ]
