# Generated by Django 4.2.18 on 2025-07-16 16:50

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0121_alter_team_contacts'),
        ('dcim', '0067_controllermanageddevicegroup_tenant'),
        ('nautobot_device_onboarding', '0009_remove_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('tcp_response', models.BooleanField(default=False)),
                ('tcp_response_datetime', models.DateTimeField(blank=True, null=True)),
                ('ssh_response', models.BooleanField(default=False)),
                ('ssh_response_datetime', models.DateTimeField(blank=True, null=True)),
                ('ssh_port', models.PositiveIntegerField(blank=True, null=True)),
                ('ssh_timeout', models.PositiveIntegerField(blank=True, default=30, null=True)),
                ('network_driver', models.CharField(blank=True, max_length=255, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('serial', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.device')),
                ('ssh_credentials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='extras.secretsgroup')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
    ]
