# Generated by Django 4.2.17 on 2024-12-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_device_onboarding", "0011_alter_onboardingconfigsyncdevices_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingconfigsyncdevices",
            name="default_connectivity_test",
            field=models.BooleanField(default=False),
        ),
    ]
