---
name: "CI"
concurrency:  # Cancel any existing runs of this workflow for this same PR
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
on: # yamllint disable-line rule:truthy rule:comments
  push:
    branches:
      - "main"
      - "develop"
  pull_request: ~

env:
  APP_NAME: "nautobot-device-onboarding"

jobs:
  ruff-format:
    runs-on: "ubuntu-latest"
    env:
      INVOKE_NAUTOBOT_DEVICE_ONBOARDING_LOCAL: "True"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v6"
        with:
          poetry-version: "2.1.3"
      - name: "Linting: ruff format"
        run: "poetry run invoke ruff --action format"
  ruff-lint:
    runs-on: "ubuntu-latest"
    env:
      INVOKE_NAUTOBOT_DEVICE_ONBOARDING_LOCAL: "True"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v6"
        with:
          poetry-version: "2.1.3"
      - name: "Linting: ruff"
        run: "poetry run invoke ruff --action lint"
  check-docs-build:
    runs-on: "ubuntu-latest"
    env:
      INVOKE_NAUTOBOT_DEVICE_ONBOARDING_LOCAL: "True"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v6"
        with:
          poetry-version: "2.1.3"
          poetry-install-options: "--only dev,docs"
      - name: "Check Docs Build"
        run: "poetry run invoke build-and-check-docs"
  poetry:
    runs-on: "ubuntu-latest"
    env:
      INVOKE_NAUTOBOT_DEVICE_ONBOARDING_LOCAL: "True"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v6"
        with:
          poetry-version: "2.1.3"
      - name: "Checking: poetry lock file"
        run: "poetry run invoke lock --check"
  yamllint:
    runs-on: "ubuntu-latest"
    env:
      INVOKE_NAUTOBOT_DEVICE_ONBOARDING_LOCAL: "True"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v6"
        with:
          poetry-version: "2.1.3"
      - name: "Linting: yamllint"
        run: "poetry run invoke yamllint"
  markdownlint:
    runs-on: "ubuntu-latest"
    env:
      INVOKE_NAUTOBOT_DEVICE_ONBOARDING_LOCAL: "True"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v6"
        with:
          poetry-version: "2.1.3"
      - name: "Linting: markdownlint"
        run: "poetry run invoke markdownlint"
  check-in-docker:
    needs:
      - "ruff-format"
      - "ruff-lint"
      - "poetry"
      - "yamllint"
      - "markdownlint"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11"]
        nautobot-version: ["2.4.20"]
    env:
      INVOKE_NAUTOBOT_DEVICE_ONBOARDING_PYTHON_VER: "${{ matrix.python-version }}"
      INVOKE_NAUTOBOT_DEVICE_ONBOARDING_NAUTOBOT_VER: "${{ matrix.nautobot-version }}"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v6"
        with:
          poetry-version: "2.1.3"
      - name: "Constrain Nautobot version and regenerate lock file"
        env:
          INVOKE_NAUTOBOT_DEVICE_ONBOARDING_LOCAL: "true"
        run: "poetry run invoke lock --constrain-nautobot-ver --constrain-python-ver=${{ matrix.python-version }}"
      - name: "Set up Docker Buildx"
        id: "buildx"
        uses: "docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2"  # v3.10.0
      - name: "Build"
        uses: "docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25"  # v5.4.0
        with:
          builder: "${{ steps.buildx.outputs.name }}"
          context: "./"
          push: false
          load: true
          tags: "${{ env.APP_NAME }}/nautobot:${{ matrix.nautobot-version }}-py${{ matrix.python-version }}"
          file: "./development/Dockerfile"
          cache-from: "type=gha,scope=${{ matrix.nautobot-version }}-py${{ matrix.python-version }}"
          cache-to: "type=gha,scope=${{ matrix.nautobot-version }}-py${{ matrix.python-version }}"
          build-args: |
            NAUTOBOT_VER=${{ matrix.nautobot-version }}
            PYTHON_VER=${{ matrix.python-version }}
            CI=true
      - name: "Linting: pylint"
        run: "poetry run invoke pylint"
      - name: "Checking: App Config"
        run: "poetry run invoke validate-app-config"
      - name: "Checking: migrations"
        run: "poetry run invoke check-migrations"
  unittest:
    needs:
      - "check-in-docker"
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10"]  # 3.12 stable is tested in unittest_report stage.
        db-backend: ["postgresql"]
        nautobot-version: ["stable"]
        include:
          - python-version: "3.11"
            db-backend: "postgresql"
            nautobot-version: "2.4.20"
          - python-version: "3.12"
            db-backend: "mysql"
            nautobot-version: "stable"
    runs-on: "ubuntu-latest"
    env:
      INVOKE_NAUTOBOT_DEVICE_ONBOARDING_PYTHON_VER: "${{ matrix.python-version }}"
      INVOKE_NAUTOBOT_DEVICE_ONBOARDING_NAUTOBOT_VER: "${{ matrix.nautobot-version }}"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v6"
        with:
          poetry-version: "2.1.3"
      - name: "Constrain Nautobot version and regenerate lock file"
        env:
          INVOKE_NAUTOBOT_DEVICE_ONBOARDING_LOCAL: "true"
        run: "poetry run invoke lock --constrain-nautobot-ver --constrain-python-ver=${{ matrix.python-version }}"
      - name: "Set up Docker Buildx"
        id: "buildx"
        uses: "docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2"  # v3.10.0
      - name: "Build"
        uses: "docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25"  # v5.4.0
        with:
          builder: "${{ steps.buildx.outputs.name }}"
          context: "./"
          push: false
          load: true
          tags: "${{ env.APP_NAME }}/nautobot:${{ matrix.nautobot-version }}-py${{ matrix.python-version }}"
          file: "./development/Dockerfile"
          cache-from: "type=gha,scope=${{ matrix.nautobot-version }}-py${{ matrix.python-version }}"
          cache-to: "type=gha,scope=${{ matrix.nautobot-version }}-py${{ matrix.python-version }}"
          build-args: |
            NAUTOBOT_VER=${{ matrix.nautobot-version }}
            PYTHON_VER=${{ matrix.python-version }}
            CI=true
      - name: "Use Mysql invoke settings when needed"
        run: "cp invoke.mysql.yml invoke.yml"
        if: "matrix.db-backend == 'mysql'"
      - name: "Run Tests"
        run: "poetry run invoke unittest"

  unittest_report:
    needs:
      - "check-in-docker"
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.12"]
        db-backend: ["postgresql"]
        nautobot-version: ["stable"]
    runs-on: "ubuntu-latest"
    permissions:
      pull-requests: "write"
      contents: "write"
    env:
      INVOKE_NAUTOBOT_DEVICE_ONBOARDING_PYTHON_VER: "${{ matrix.python-version }}"
      INVOKE_NAUTOBOT_DEVICE_ONBOARDING_NAUTOBOT_VER: "${{ matrix.nautobot-version }}"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v6"
        with:
          poetry-version: "2.1.3"
      - name: "Constrain Nautobot version and regenerate lock file"
        env:
          INVOKE_NAUTOBOT_DEVICE_ONBOARDING_LOCAL: "true"
        run: "poetry run invoke lock --constrain-nautobot-ver --constrain-python-ver=${{ matrix.python-version }}"
      - name: "Set up Docker Buildx"
        id: "buildx"
        uses: "docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2"  # v3.10.0
      - name: "Build"
        uses: "docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25"  # v5.4.0
        with:
          builder: "${{ steps.buildx.outputs.name }}"
          context: "./"
          push: false
          load: true
          tags: "${{ env.APP_NAME }}/nautobot:${{ matrix.nautobot-version }}-py${{ matrix.python-version }}"
          file: "./development/Dockerfile"
          cache-from: "type=gha,scope=${{ matrix.nautobot-version }}-py${{ matrix.python-version }}"
          cache-to: "type=gha,scope=${{ matrix.nautobot-version }}-py${{ matrix.python-version }}"
          build-args: |
            NAUTOBOT_VER=${{ matrix.nautobot-version }}
            PYTHON_VER=${{ matrix.python-version }}
            CI=true
      - name: "Copy credentials"
        run: "cp development/creds.example.env development/creds.env"
      - name: "Use Mysql invoke settings when needed"
        run: "cp invoke.mysql.yml invoke.yml"
        if: "matrix.db-backend == 'mysql'"
      - name: "Run Tests"
        run: "poetry run invoke unittest --coverage"
      - name: "Generate Coverage Comment"
        if: >
          contains(fromJson('["develop","ltm-1.6"]'), github.base_ref) &&
          (github.head_ref != 'main') && (!startsWith(github.head_ref, 'release'))
        id: "coverage_comment"
        uses: "py-cov-action/python-coverage-comment-action@d1ff8fbb5ff80feedb3faa0f6d7b424f417ad0e1"  # v3.30
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MINIMUM_GREEN: 90
          MINIMUM_ORANGE: 80
          ANNOTATE_MISSING_LINES: true
          ANNOTATION_TYPE: "warning"
      - name: "Store Pull Request comment to be posted"
        if: >
          contains(fromJson('["develop","ltm-1.6"]'), github.base_ref) &&
          (github.head_ref != 'main') && (!startsWith(github.head_ref, 'release'))
        uses: "actions/upload-artifact@v4"
        with:
          name: "python-coverage-comment-action"
          path: "python-coverage-comment-action.txt"

  changelog:
    if: >
      contains(fromJson('["develop","ltm-1.6"]'), github.base_ref) &&
      (github.head_ref != 'main') && (!startsWith(github.head_ref, 'release'))
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: "0"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v6"
        with:
          poetry-version: "2.1.3"
      - name: "Check for changelog entry"
        run: |
          git fetch --no-tags origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
          poetry run towncrier check --compare-with origin/${{ github.base_ref }}
